project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "!/tools/quarto/"

website:
  title: UVic Spring School 2023
  image: /img/sfudrac_logo.png
  favicon: /img/sfu_favicon.png
  site-url: https://2023uvic.netlify.app/
  repo-url: https://github.com/WestDRI/2023uvic
  reader-mode: true
  page-navigation: true
  page-footer:
    center:
      - text: About
        href: about.qmd
      - text: Calendar
        href: calendar.qmd
        aria-label: WestDRI training calendar
      - text: Newsletter
        href: newsletter.qmd
        aria-label: WestDRI Newsletter
      - href: contact.qmd
        aria-label: WestDRI Contact
      - text: Wiki
        href: https://docs.alliancecan.ca/wiki/Technical_documentation
    right:
      - icon: github
        href: https://github.com/WestDRI
        aria-label: WestDRI GitHub
      - icon: youtube
        href: https://www.youtube.com/channel/UCfgds4Qf7VFOv4ORRvFFmhw
        aria-label: WestDRI YouTube
  navbar:
    background: light
    logo: /img/sfudrac_logo.png
    logo-alt: "SFU & DRAC logos"
    title: false
    left:
      - text: Bash
        href: bash/index.qmd
      - text: HPC
        href: hpc/index.qmd
      - text: Intro R
        href: r_intro/index.qmd
      - text: Parallel R
        href: r_parallel/index.qmd
      - text: Parallel Julia
        href: julia/index.qmd
      - text: PyTorch
        href: ml/index.qmd
      - text: ParaView
        href: scivis/index.qmd
  sidebar:
    - id: bash
      contents:
        - section:
          contents:
            - bash/index.qmd
        # - text: <b><em>Bash & the Unix shell</em></b>
        #   href: bash/index.qmd
        #   contents:
    - id: hpc
      contents:
        - section:
          contents:
            - hpc/index.qmd
        # - text: <b><em>Introduction to HPC</em></b>
        #   href: hpc/index.qmd
        #   contents:
    - id: r_intro
      contents:
        - section:
          contents:
            - r_intro/index.qmd
        # - text: <em><b>Getting started with R</b></em>
        #   href: r_intro/index.qmd
        #   contents: 
        #     - text: "R: why and for whom?"
        #       href: r_intro/why.qmd
        #     - text: "R: the basics"
        #       href: r_intro/basics.qmd
        #     - text: Packages
        #       href: r_intro/packages.qmd
        #     - text: Glimpse at the tidyverse
        #       href: r_intro/tidyverse.qmd
        #     - text: Resources
        #       href: r_intro/resources.qmd
    - id: r_parallel
      contents:
        - section:
          contents:
            - r_parallel/index.qmd
        # - text: <b><em>Parallel R</em></b>
        #   href: r_parallel/index.qmd
        #   contents: 
        #     - text: Measuring performance
        #       href: r_parallel/performance.qmd
        #     - text: Running R on HPC clusters
        #       href: r_parallel/clusters.qmd
        #     - text: Types of parallelism
        #       href: r_parallel/parallel_types.qmd
        #     - text: Running R code in parallel
        #       href: r_parallel/parallel_r.qmd
        #     - text: Parallel loops
        #       href: r_parallel/parallel_loops.qmd
        #     - text: Partitioning data
        #       href: r_parallel/partition.qmd
        #     - text: Writing C++ in R with Rcpp
        #       href: r_parallel/rcpp.qmd
    - id: julia
      contents:
        - section:
          contents:
            - julia/index.qmd
        # - text: <b><em>Parallel Julia</em></b>
        #   href: julia/index.qmd
        #   contents: 
        #     - text: Introduction to Julia
        #       href: julia/intro-language.qmd
    - id: ml
      contents:
        - section:
          contents:
            - ml/index.qmd
        # - text: <b><em>Introduction to PyTorch</em></b>
        #   href: ml/index.qmd
        #   contents: 
        #     - text: Overarching concept of DL
        #       href: ml/concept.qmd
        #     - text: "Concepts: AI, ML, DL, NN"
        #       href: ml/nn.qmd
        #     - text: Which framework to choose?
        #       href: ml/choosing_frameworks.qmd
        #     - text: High-level frameworks
        #       href: ml/high_level_frameworks.qmd
        #     - text: Automatic differentiation
        #       href: ml/autograd.qmd
        #     - text: Classifying the MNIST
        #       href: ml/mnist.qmd
        #     - text: Building a model
        #       href: ml/nn_building.qmd
        #     - text: Training a model
        #       href: ml/nn_training.qmd
        #     - text: Audio DataLoader
        #       href: ml/audio_dataloader.qmd
        #     - text: ML on production clusters
        #       href: ml/hpc.qmd
        #     - text: Finding pre-trained models
        #       href: ml/pretrained_models.qmd
        #     - text: Creating checkpoints
        #       href: ml/checkpoints.qmd
        #     - text: Resources
        #       href: ml/resources.qmd
    - id: scivis
      contents:
        - section:
          contents:
            - scivis/index.qmd
        # - text: <b><em>SciVis with ParaView</em></b>
        #   href: scivis/index.qmd
        # - contents:

format:
  html:
    toc: true
    toc-title: "<em>On this page:</em>"
    toc-depth: 5
    theme:
      light: [cosmo, theme.scss]
    code-overflow: wrap
    css: styles.css
    link-external-newwindow: true
    reference-location: margin
    fig-cap-location: margin

execute:
  freeze: auto
  cache: true
  error: true
  echo: true
